apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: my-app:1.0.0
      ports:
        - containerPort: 3000
    readinessProbe:
      httpGet:
        path: /api/ready
        port: 8080
      initialDelaySeconds: 20
      periodSeconds: 3
      timeoutSeconds: 3