apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: my-app:1.0.0
      volumeMounts:
      - name: property
        mountPath: /app/resources
    volumnes:
    - name: property
      configMap:
        name: my-config
        items:
        - key: my-property
          path: application.properties
env:
- name: MY_DB_PASSWORD
  valueFrom:
    scretKeyRef:
      name: my-app-secret
      key: db-password
- name: MY_SECRET_API_KEY
  valueForm:
    secretKeyRef:
      name: my-app-secret
      key: secret-api-key