apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  volumes: #(1)
  - name: temp-volume
    emptyDir: {}
  containers:
  - name: first-container
    image: my-app:1.0.0
    volumeMounts: #(2)
    - mountPath: /temp
      name: temp-volume
  - name: second-container
    image: another-app:1.0.0
    volumeMounts: #(3)
    - mountPath: /storages/files
      name: temp-volume